---
- name: Initializing DB
  shell: "{{ item }}"
  loop:
    - " /usr/pgsql-15/bin/postgresql-15-setup initdb"
    - " sudo systemctl enable postgresql-15"
    - " sudo systemctl start postgresql-15"
