---
- name: Create dir for git project
  file:
    path: /git/
    state: directory
    mode: '0755'
- name: Git download
  ansible.builtin.git:
    repo: 'https://github.com/NickVG/otus-postgres.git'
    dest: "{{ dir }}"
- name: Run docker-compose
  shell: "{{ item }}"
#  register: output
#  failed_when: false
#  ignore_errors: True
  args:
    chdir: "{{ dir }}/Lecture03/ansible/roles/db/files/"
  loop:
    - "bash docker-compose.sh > /dev/null 2>&1"

#    - 'docker compose -f {{ dir }}/Lecture03/ansible/roles/db/files/docker-compose.yml up & > /dev/null 2>&1'

