- name: Create backup directory
  file:
    state: directory
    path: /pg_backup/
    owner: postgres
    group: postgres
    mode: '0700'
- name: Download and Unarchive Big Database flights
  ansible.builtin.unarchive:
    src: https://edu.postgrespro.ru/demo-big.zip
    dest: /pg_backup/
    remote_src: yes
#- name: Download Big Database flights
#  ansible.builtin.get_url:
#    url: https://edu.postgrespro.ru/demo-big.zip
#    dest: /pg_backup/demo-big.zip
#    mode: '0700'
- name: Create Database, backup and restore data via pg_dump
  script: "{{ item }}"
  loop:
    - "deploy_db.sh"
